version: '3.8'
services:

  word-bank-mysql:
    image: mysql:latest
    container_name: word-bank-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: word-bank-db
      MYSQL_USER: word-bank-user1
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

volumes:
  mysql:
    driver: local

networks:
  word-bank-network:
    driver: bridge